[package]
name = "mdbook-structured-core"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
json-syntax.workspace = true
rlsp-yaml-parser.workspace = true

[dev-dependencies]
mdbook-markdown.workspace = true
proptest.workspace = true
scraper.workspace = true
serde.workspace = true
serde_json.workspace = true
